version: "3.7"

services:
  mysql-database:
    image: arm64v8/mysql:oracle
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: voting-app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .mysql:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql-database
    environment:
      PMA_HOST: mysql-database
    ports:
      - 8080:80
  redis:
    image: arm64v8/redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - .redis:/data
    ports:
      - 6379:6379

  rabbit-mq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    restart: unless-stopped
    volumes:
      - .rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 10
    ports:
      - 5672:5672
      - 15672:15672
  voting-app:
    build: .
    container_name: voting-app
    restart: unless-stopped
    environment:
      PORT: 3000
      SWAGGER_USERNAME: shuvro
      SWAGGER_PASSWORD: 1010
      RABBIT_MQ_URL: amqp://guest:guest@rabbit-mq:5672
      RABBIT_MQ_POCKER_EXCHANGE: poker_exchange
      RABBIT_MQ_POCKER_ROUTING_KEY: poker_routing_key
      RABBIT_MQ_POCKER_QUEUE: poker_queue

      RABBITMQ_VOTING_EXCHANGE: redis_voting_exchange
      RABBITMQ_VOTING_ROTING_KEY: redis_voting_routing_key
      RABBITMQ_VOTING_QUEUE: redis_voting_queue

      DB_DRIVER: mysql
      DB_HOST: mysql-database
      DB_PORT: 3306
      DB_PASSWORD: root
      DB_USER: root
      DB_NAME: voting-app
      RUN_MIGRATION: true

      # REDIS
      REDIS_URL: redis
      REDIS_KEY_PREFIX: voting
      REDIS_DB_INDEX: 0

      JWT_SECRET: shuvro
      VOTING_TOKEN_VALIDITY_IN_MIN: 10
    depends_on:
      - redis
      - mysql-database
      - rabbit-mq
    ports:
      - 3000:3000

