version: "3.7"

services:
  mysql-database:
    image: arm64v8/mysql:oracle
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: qpro-task
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .mysql:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql-database
    environment:
      PMA_HOST: mysql-database
    ports:
      - 8080:80
  redis:
    image: arm64v8/redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - .redis:/data
    ports:
      - 6379:6379

  qpro-task:
    build: .
    container_name: qpro-task
    restart: unless-stopped
    environment:
      PORT: 3000

      DB_DRIVER: mysql
      DB_HOST: mysql-database
      DB_NAME: qpro-task
      DB_PASSWORD: root
      DB_PORT: 3306
      DB_USER: root
      RUN_MIGRATION: true

      APP_SECRET: qpro
      REDIS_URL: redis
      REDIS_KEY_PREFIX: qpro
      REDIS_DB_INDEX: 0
    depends_on:
      - redis
      - mysql-database
    ports:
      - 3000:3000


